name: Build Python Project

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install pywin
        run: |
          pip install pywin32
          python Scripts/pywin32_postinstall.py -install
        
      - name: Build exe with Pyinstaller and upload
        uses: sayyid5416/pyinstaller@v1
        with:
          spec: 'build.spec'
          requirements: 'requirements.txt'
          python_ver: '3.6'
          pyinstaller_ver: '==5.13.2'
          upload_exe_with_name: 'Debot'
